In [ ]:
!pip install twstock

import twstock as t

import pandas as p

import plotly.express as e

Requirement already satisfied: twstock in /usr/local/lib/python3.10/dist-packages (1.3.1)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from twstock) (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->twstock) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->twstock) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->twstock) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->twstock) (2023.11.17)

In [1]:
import requests

from io import StringIO

import pandas as pd

import numpy as np

#查詢日期

datestr = '20220819'

r = requests.post('http://www.twse.com.tw/exchangeReport/MI_INDEX?response=csv&date=' + datestr + '&type=ALL')

df = pd.read_csv(StringIO("\n".join([i.translate({ord(c): None for c in ' '})

  for i in r.text.split('\n')

  if len(i.split('",')) == 17 and i[0] != '='])), header=0 , thousands=",")

#條件篩選，5<本益比<15 且 收盤價<300 且 (成交股數/1000）>10000張

df.loc[(pd.to_numeric(df['本益比'], errors='coerce') < 15) & (pd.to_numeric(df['本益比'], errors='coerce') > 5) & (pd.to_numeric(df['收盤價'], errors='coerce') < 30) & (pd.to_numeric(df['成交股數'], errors='coerce')/1000 > 10000)]

,證券代號,證券名稱,成交股數,成交筆數,成交金額,開盤價,最高價,最低價,收盤價,漲跌(+/-),漲跌價差,最後揭示買價,最後揭示買量,最後揭示賣價,最後揭示賣量,本益比,Unnamed: 16
204,2002,中鋼,14754032,5926,429985254,29.10,29.25,29.00,29.20,NaN,0.00,29.15,265,29.20,12,7.66,NaN
213,2014,中鴻,10642480,4223,294578432,28.00,28.00,27.40,27.55,-,0.15,27.50,76,27.55,8,11.15,NaN
273,2324,仁寶,10739187,3729,245496329,22.60,23.00,22.60,22.90,+,0.15,22.90,46,22.95,141,8.51,NaN
292,2353,宏碁,15021648,4961,330965154,22.15,22.25,21.80,22.15,-,0.20,22.15,105,22.20,165,7.22,NaN
332,2409,友達,169967535,36196,2840322761,15.70,17.15,15.70,16.95,+,1.25,16.90,1143,16.95,413,5.50,NaN
434,2610,華航,44704468,14849,957013137,21.65,21.70,21.25,21.40,-,0.30,21.35,389,21.40,372,9.03,NaN
487,2883,開發金,18343159,5431,254270049,13.85,13.90,13.80,13.90,+,0.05,13.85,1665,13.90,290,7.35,NaN
490,2885,元大金,15859655,5536,328598266,20.80,20.85,20.60,20.80,NaN,0.00,20.75,13,20.80,543,7.97,NaN
496,2888,新光金,21093580,4043,189512604,8.94,9.04,8.92,9.02,+,0.06,9.01,35,9.02,51,7.84,NaN
500,2890,永豐金,14181907,2891,243888521,17.15,17.30,17.05,17.30,+,0.05,17.25,79,17.30,1355,12.27,NaN
501,2891,中信金,30839483,9933,756237138,24.40,24.70,24.15,24.60,+,0.15,24.55,512,24.60,129,9.68,NaN
612,3481,群創,218115820,37896,2654463011,11.40,12.45,11.35,12.45,+,1.10,12.45,609858,--,0,6.04,NaN
906,8105,凌巨,13321933,4423,182208694,13.20,14.00,13.00,13.75,+,0.65,13.75,81,13.80,31,10.42,NaN
963,9907,統一實,11537409,5138,234385726,20.60,20.80,20.00,20.20,-,0.30,20.20,107,20.25,161,11.81,NaN